# Generated by Django 5.1.1 on 2024-10-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History Record', 'verbose_name_plural': 'History Records'},
        ),
    ]
