# Generated by Django 5.1.1 on 2025-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_alter_history_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/'),
        ),
    ]
